### ISSUE TITLE
Insert Images Included in CSS StyleSheet

### ISSUE THREAD

**Issue by nkoterba** [substack/insert-css#11]
It's possible I'm missing something...but let's say I use an image in my CSS stylesheet for a background:

**styles.css**
```javascript
body {
    background-image: url('img/disk.png');
}
```

And my file structure is as follows:
* index.html
* main.js
* css
   * styles.css
   * img
      * disk.png

When I insert the css file in main.js all works fine when I browserify my bundle:

**main.js**
```javascript
var fs = require('fs');
var insertCss = require('insert-css');

var css = fs.readFileSync('./css/styles.css');
insertCss(css);
```

However, in the browser the webpage gives 404 (resource not found), because it's trying to find 
```javascript
http://.../<location of index.html>/img/disk.png
```

Now I can resolve the issue by fully-qualifying the relative path in my styles.css file, e.g.:
```javascript
body {
    background-image: url('./css/img/disk.png');
}
```

However, many 3rd party controls and themes (e.g., JQuery), just use img/xxx.png and I don't want to go through and modify *all* the image url includes in the CSS file to get things to work.

Any suggestions or advice?

Thanks!

**Comment by vvo** [comment]
cannot be fixed at the insert-css level.

relative links in external CSS files are related to the CSS file itself.

When using insert-css, since the CSS content is inlined in the DOM then the new referential on how to load images is the HTML location.

You can solve this at build time by resolving images to the root
